using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

if (args.Length != 2) return 2;

var schemaDirectory = Path.GetFullPath(args[0]);
var outputFile = Path.GetFullPath(args[1]);
var schemaFile = Directory.EnumerateFiles(schemaDirectory, "protocol*.json")
    .OrderByDescending(Path.GetFileName)
    .First();
using var document = JsonDocument.Parse(File.ReadAllBytes(schemaFile));
var protocolBuild = Path.GetFileNameWithoutExtension(schemaFile)[8..];
var pythonFile = Path.Combine(schemaDirectory, $"protocol{protocolBuild}.py");
var declarations = EnumerateObjects(document.RootElement)
    .Where(decl => decl.TryGetProperty("fullname", out _) && decl.TryGetProperty("type_info", out _))
    .Where(decl => !string.IsNullOrWhiteSpace(decl.GetProperty("fullname").GetString()))
    .ToDictionary(decl => decl.GetProperty("fullname").GetString()!, StringComparer.Ordinal);

var tracker = declarations.Values
    .Where(decl => decl.GetProperty("fullname").GetString()!.Contains(".Replay.Tracker.S", StringComparison.Ordinal))
    .Where(decl => decl.GetProperty("type_info").GetProperty("type").GetString() == "StructType")
    .OrderBy(decl => decl.GetProperty("fullname").GetString())
    .ToArray();

var source = new StringBuilder("""
// <auto-generated />
#nullable enable
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Biz.Bizadm.SC2ReplayTrace.Protocol.Generated;

/// <summary>생성된 tracker 이벤트가 구현하는 공통 인터페이스입니다.</summary>
public interface IGeneratedTrackerEvent
{
    /// <summary>공식 이벤트 이름입니다.</summary>
    string EventName { get; }
    /// <summary>이름으로 정수 필드 값을 가져옵니다.</summary>
    int? GetInt(string name);
    /// <summary>이름으로 문자열 필드 값을 가져옵니다.</summary>
    string? GetString(string name);
}

""");

foreach (var declaration in tracker)
{
    var fullName = declaration.GetProperty("fullname").GetString()!;
    var className = "S" + Sanitize(fullName[(fullName.LastIndexOf('.') + 1)..]);
    source.AppendLine("/// <summary>공식 스키마에서 생성된 tracker 이벤트입니다.</summary>");
    source.AppendLine($"public sealed partial class {className} : IGeneratedTrackerEvent");
    source.AppendLine("{");
    source.AppendLine("    /// <summary>공식 이벤트 이름입니다.</summary>");
    source.AppendLine($"    public string EventName => \"{fullName}\";");
    foreach (var field in declaration.GetProperty("type_info").GetProperty("fields").EnumerateArray())
    {
        var name = field.GetProperty("name").GetString()!;
        source.AppendLine($"    /// <summary>공식 이벤트 필드 <c>{name}</c>입니다.</summary>");
        source.AppendLine($"    public {TypeName(field.GetProperty("type_info"))}? {Sanitize(name)} {{ get; init; }}");
    }
    source.AppendLine("    /// <summary>이름으로 정수 필드 값을 가져옵니다.</summary>");
    source.AppendLine("    public int? GetInt(string name) => name switch");
    source.AppendLine("    {");
    foreach (var field in declaration.GetProperty("type_info").GetProperty("fields").EnumerateArray())
    {
        var name = field.GetProperty("name").GetString()!;
        if (TypeName(field.GetProperty("type_info")) == "int")
            source.AppendLine($"        \"{name}\" => {Sanitize(name)},");
    }
    source.AppendLine("        _ => null");
    source.AppendLine("    };");
    source.AppendLine("    /// <summary>이름으로 문자열 필드 값을 가져옵니다.</summary>");
    source.AppendLine("    public string? GetString(string name) => name switch");
    source.AppendLine("    {");
    foreach (var field in declaration.GetProperty("type_info").GetProperty("fields").EnumerateArray())
    {
        var name = field.GetProperty("name").GetString()!;
        if (TypeName(field.GetProperty("type_info")) == "string")
            source.AppendLine($"        \"{name}\" => {Sanitize(name)},");
    }
    source.AppendLine("        _ => null");
    source.AppendLine("    };");
    source.AppendLine("    /// <summary>JSON 노드에서 이벤트를 생성합니다.</summary>");
    source.AppendLine("    public static " + className + " FromJson(JsonNode node) => new()");
    source.AppendLine("    {");
    foreach (var field in declaration.GetProperty("type_info").GetProperty("fields").EnumerateArray())
    {
        var name = field.GetProperty("name").GetString()!;
        var property = Sanitize(name);
        source.AppendLine($"        {property} = node[\"{name}\"]?.GetValue<{TypeName(field.GetProperty("type_info"))}>(),");
    }
    source.AppendLine("    };");
    source.AppendLine("}");
}

source.AppendLine("/// <summary>생성된 tracker 이벤트를 생성합니다.</summary>");
source.AppendLine("public static class GeneratedTrackerEventFactory");
source.AppendLine("{");
source.AppendLine("    /// <summary>공식 이벤트 이름에 해당하는 이벤트를 생성합니다.</summary>");
source.AppendLine("    public static IGeneratedTrackerEvent? Create(string eventName, JsonNode data) => eventName switch");
source.AppendLine("    {");
foreach (var declaration in tracker)
{
    var fullName = declaration.GetProperty("fullname").GetString()!;
    var className = "S" + Sanitize(fullName[(fullName.LastIndexOf('.') + 1)..]);
    source.AppendLine($"        \"{fullName}\" => {className}.FromJson(data),");
}
source.AppendLine("        _ => null");
source.AppendLine("    };");
source.AppendLine("}");

source.AppendLine("/// <summary>공식 프로토콜 이벤트 매핑을 제공합니다.</summary>");
source.AppendLine("public static class GeneratedProtocolMaps");
source.AppendLine("{");
AppendEventMap("GameEventTypes", "game_event_types");
AppendEventMap("MessageEventTypes", "message_event_types");
source.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);
File.WriteAllText(outputFile, source.ToString());
return 0;

IEnumerable<JsonElement> EnumerateObjects(JsonElement element)
{
    if (element.ValueKind == JsonValueKind.Object)
    {
        yield return element;
        foreach (var property in element.EnumerateObject())
            foreach (var child in EnumerateObjects(property.Value))
                yield return child;
    }
    else if (element.ValueKind == JsonValueKind.Array)
    {
        foreach (var child in element.EnumerateArray())
            foreach (var nested in EnumerateObjects(child))
                yield return nested;
    }
}

void AppendEventMap(string propertyName, string pythonName)
{
    source.AppendLine($"    /// <summary>{pythonName} 이벤트 매핑입니다.</summary>");
    source.AppendLine($"public static IReadOnlyDictionary<int, (int TypeId, string Name)> {propertyName} {{ get; }} = new Dictionary<int, (int, string)>");
    source.AppendLine("{");
    if (File.Exists(pythonFile))
    {
        var text = File.ReadAllText(pythonFile);
        var block = Regex.Match(text, $@"{pythonName}\s*=\s*\{{(?<body>.*?)\n\}}", RegexOptions.Singleline).Groups["body"].Value;
        foreach (Match match in Regex.Matches(block, @"(?m)^\s*(\d+):\s*\((\d+),\s*'([^']+)'"))
            source.AppendLine($"    [{match.Groups[1].Value}] = ({match.Groups[2].Value}, \"{match.Groups[3].Value}\"),");
    }
    source.AppendLine("};");
}

string TypeName(JsonElement type)
{
    var kind = type.GetProperty("type").GetString();
    if (kind == "UserType" &&
        declarations.TryGetValue(type.GetProperty("fullname").GetString()!, out var declaration))
        return TypeName(declaration.GetProperty("type_info"));

    return kind switch
    {
        "BoolType" => "bool",
        "IntType" or "UintType" or "EnumType" => "int",
        "Real32Type" or "Real64Type" => "double",
        "StringType" or "AsciiStringType" or "FourCCType" => "string",
        "BlobType" or "BitArrayType" => "byte[]",
        _ => "JsonNode"
    };
}

string Sanitize(string value)
{
    var result = new string(value.Select(character => char.IsLetterOrDigit(character) ? character : '_').ToArray());
    return result.Length > 0 && char.IsDigit(result[0]) ? "_" + result : result;
}
