<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>Biz.Bizadm.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>Biz.Bizadm.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Version>1.0.1</Version>
		<Authors>SeongSikChae</Authors>
		<RepositoryUrl>https://github.com/SeongSikChae/SC2ReplayTrace.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<Description>스타크래프트 2 리플레에서 게임 상태 및 이벤트 추척</Description>
		<PackageId>$(AssemblyName)</PackageId>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageTags>StarCraft II;SC2;replay;parser;MPQ;s2protocol</PackageTags>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\THIRD-PARTY-NOTICES.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="Protocol\S2Protocol.LICENSE" Pack="True" PackagePath="protocol" />
		<EmbeddedResource Include="Protocol\Schemas\protocol*.json" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SharpCompress" Version="0.50.4" />
	  <PackageReference Include="SharpZipLib" Version="1.4.2" />
	</ItemGroup>

</Project>
